/**
 * alumniData.ts — AUTO-GENERATED
 * Source : public/data/alumni.xlsx.xlsx
 * Generated : 2026-07-14T12:37:49.894Z
 *
 * DO NOT EDIT MANUALLY.
 * To regenerate run: npm run alumni:convert
 */

import type { AlumniRecord } from '../types/alumni';

export const ALUMNI_DATA: AlumniRecord[] = [
  {
    "id": "1",
    "fullName": "Dabanjan Kusari",
    "nickname": "Deva",
    "batch": "2008",
    "designation": "",
    "organization": "Kingdom Organic Farm Pvt Ltd",
    "profession": "Entrepreneur",
    "qualification": "B.Tech ( Electrical & Electronics )",
    "city": "Gurugram",
    "country": "India",
    "photoUrl": "https://drive.google.com/thumbnail?id=1OVNqcJsLF4AnXMZKoszWroimuhcl-GqV&sz=w300",
    "linkedinUrl": "https://www.linkedin.com/in/debanjan-kusari-60044698?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
    "facebookUrl": "",
    "registeredAt": "2026-03-26"
  },
  {
    "id": "2",
    "fullName": "Adarsh Mohan Verma",
    "nickname": "Adarsh",
    "batch": "1994",
    "designation": "CEO (Gujarat)",
    "organization": "Bharti Airtel Ltd.",
    "profession": "Service in Pvt Ltd company",
    "qualification": "MBA",
    "city": "Ahmedabad",
    "country": "India",
    "photoUrl": "https://drive.google.com/thumbnail?id=1gD_O1i-haiZ3Y6JhMoCNRUUUIwatr0ya&sz=w300",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-03-26"
  },
  {
    "id": "3",
    "fullName": "Shobhit Dhaka",
    "nickname": "Shobhit Dhaka",
    "batch": "1993",
    "designation": "Deputy General Manager",
    "organization": "TATA Communications Ltd",
    "profession": "",
    "qualification": "",
    "city": "Greater Noida",
    "country": "India",
    "photoUrl": "https://drive.google.com/thumbnail?id=1V3ieI8AKm6xsXVSdpX0F40RAWPlkyFAw&sz=w300",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-03-26"
  },
  {
    "id": "4",
    "fullName": "Deepti Gupta",
    "nickname": "Deepti",
    "batch": "1999",
    "designation": "Deputy Director",
    "organization": "Confederation of Indian Industry",
    "profession": "Job",
    "qualification": "MBA",
    "city": "Gurugram",
    "country": "India",
    "photoUrl": "https://drive.google.com/thumbnail?id=1IjoFY1oRjB6Vq7zATfbOUU283OEIyw2S&sz=w300",
    "linkedinUrl": "https://www.linkedin.com/in/deepti-gupta-mehra-13924255/",
    "facebookUrl": "",
    "registeredAt": "2026-03-26"
  },
  {
    "id": "5",
    "fullName": "Praveen Bhal",
    "nickname": "Bittoo",
    "batch": "1990",
    "designation": "Colonel",
    "organization": "Defence",
    "profession": "Defence",
    "qualification": "MBA",
    "city": "Delhi",
    "country": "India",
    "photoUrl": "https://drive.google.com/thumbnail?id=1oYfFHk7W6HekB5VRv7uij8kyoovQltUi&sz=w300",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-03-26"
  },
  {
    "id": "6",
    "fullName": "Gaurav Chandel",
    "nickname": "GC, Chandu",
    "batch": "1997",
    "designation": "Operation & Sourcing Manager - India & Sri Lanka",
    "organization": "Delta Galil Industries Limited",
    "profession": "Service",
    "qualification": "Masters",
    "city": "Noida Extension",
    "country": "India",
    "photoUrl": "https://drive.google.com/thumbnail?id=1Ms9h9tjSiA67tu4tdq7CghG1wQuH5IZ1&sz=w300",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-03-26"
  },
  {
    "id": "7",
    "fullName": "Amaresh chandel",
    "nickname": "Amru",
    "batch": "1992",
    "designation": "Breeding Partnerships Lead",
    "organization": "Bayer",
    "profession": "Scientist",
    "qualification": "PhD Agriculture",
    "city": "Hyderabad",
    "country": "India",
    "photoUrl": "https://drive.google.com/thumbnail?id=1o8qBXeU-lwBiSwL9kqwdeTDddZ8qknJr&sz=w300",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-03-26"
  },
  {
    "id": "8",
    "fullName": "Rana Atheya",
    "nickname": "Rana",
    "batch": "1998",
    "designation": "Founder",
    "organization": "DogSpot",
    "profession": "Entrepreneur",
    "qualification": "MBA",
    "city": "Bhimtal",
    "country": "India",
    "photoUrl": "https://drive.google.com/thumbnail?id=1kST78Uc_HQYygf4_RZo2xw-H-Wcv_HfO&sz=w300",
    "linkedinUrl": "https://www.linkedin.com/in/ratheya/",
    "facebookUrl": "https://www.facebook.com/ratheya",
    "registeredAt": "2026-03-26"
  },
  {
    "id": "9",
    "fullName": "Anupam Jain",
    "nickname": "Anupam",
    "batch": "1994",
    "designation": "AVP",
    "organization": "Reliance Retail",
    "profession": "Service",
    "qualification": "MBA",
    "city": "Mumbai",
    "country": "India",
    "photoUrl": "https://drive.google.com/thumbnail?id=1aZYQcncbCk6IBZwoyNsVs6vz4Bg3X3SZ&sz=w300",
    "linkedinUrl": "https://www.linkedin.com/in/anupam9936355155?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "facebookUrl": "https://www.facebook.com/share/17PMjzFgA7/",
    "registeredAt": "2026-03-26"
  },
  {
    "id": "10",
    "fullName": "Saurabh Srivastava",
    "nickname": "Saurabh",
    "batch": "1997",
    "designation": "Zonal Head- Investment Advisors",
    "organization": "ICICI Bank Ltd",
    "profession": "Wealth Manager, Private Banking, Investment Management",
    "qualification": "MBA",
    "city": "Noida",
    "country": "India",
    "photoUrl": "https://drive.google.com/thumbnail?id=1K8KH20j0IxDJ_SqsZMCT8kGEY7iRc_oi&sz=w300",
    "linkedinUrl": "https://www.linkedin.com/in/saurabh-srivastava-3030766?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "facebookUrl": "",
    "registeredAt": "2026-03-26"
  },
  {
    "id": "11",
    "fullName": "Manav Deshwal",
    "nickname": "—",
    "batch": "1991",
    "designation": "Colonel",
    "organization": "Indian Army",
    "profession": "Veterinarian",
    "qualification": "MVSc Veterinary Pathology",
    "city": "Meerut",
    "country": "India",
    "photoUrl": "https://drive.google.com/thumbnail?id=1vYc8OgUjIOCSDDMm5w2Y1CmpYikIodHZ&sz=w300",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-03-26"
  },
  {
    "id": "12",
    "fullName": "Ambuj",
    "nickname": "Dheeru",
    "batch": "2007",
    "designation": "Lt Col",
    "organization": "Indian Army",
    "profession": "Officer",
    "qualification": "Post Graduate",
    "city": "Delhi",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-03-26"
  },
  {
    "id": "13",
    "fullName": "Bohitesh Misra",
    "nickname": "Bohi",
    "batch": "1984",
    "designation": "Co-Founder and CTO",
    "organization": "Avexa Systems",
    "profession": "IT / Startup",
    "qualification": "B. Tech (CSE), MBA",
    "city": "Ghaziabad",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "",
    "facebookUrl": "https://www.facebook.com/bohitesh.misra",
    "registeredAt": "2026-03-26"
  },
  {
    "id": "14",
    "fullName": "Ishu Agrawal",
    "nickname": "None",
    "batch": "1991",
    "designation": "Vice President",
    "organization": "Vivaldis Health and Foods Pvt Ltd",
    "profession": "Marketing and Sales",
    "qualification": "Post graduation",
    "city": "Noida",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-03-26"
  },
  {
    "id": "15",
    "fullName": "Chitra Chandel",
    "nickname": "No nickname",
    "batch": "1995",
    "designation": "Academic Coordinator",
    "organization": "Seth Anandram Jaipuria School",
    "profession": "Teaching",
    "qualification": "B.Ed.",
    "city": "Greater Noida",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "https://www.linkedin.com/in/chitra-singh-428545330/",
    "facebookUrl": "",
    "registeredAt": "2026-03-26"
  },
  {
    "id": "16",
    "fullName": "Vinti Manglik",
    "nickname": "Sangeeta",
    "batch": "1983",
    "designation": "Director",
    "organization": "Thinkers Club and Zenvoya.ai",
    "profession": "Entrepreneur",
    "qualification": "MTech",
    "city": "Gurugram",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-03-26"
  },
  {
    "id": "17",
    "fullName": "Deepshikha Ghosh",
    "nickname": "Deepshikha",
    "batch": "1999",
    "designation": "NA",
    "organization": "NA",
    "profession": "Human Resources",
    "qualification": "PGDBM",
    "city": "Noida",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-03-26"
  },
  {
    "id": "18",
    "fullName": "Pritha Dubey",
    "nickname": "PD",
    "batch": "1994",
    "designation": "Founder",
    "organization": "SUCCESS VITAMIN",
    "profession": "Self Employed",
    "qualification": "PGDBA",
    "city": "Gurugram",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "https://www.linkedin.com/in/pritha-dubey-salesspeaker?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    "facebookUrl": "",
    "registeredAt": "2026-03-27"
  },
  {
    "id": "19",
    "fullName": "Ruchir Maheshwari",
    "nickname": "Rinkoo",
    "batch": "1994",
    "designation": "Director & Head - Urology, Robotics & Kidney Transplant",
    "organization": "Fortis Healthcare - Manesar/ Vasant Kunj",
    "profession": "Medical Doctor (Urology, Robotics & Kidney Transplant)",
    "qualification": "M.Ch. (Urology)",
    "city": "Gurugram",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "http://linkedin.com/in/ruchir-maheshwari-0a967a14",
    "facebookUrl": "https://m.facebook.com/ruchir.maheshwari.9/",
    "registeredAt": "2026-03-27"
  },
  {
    "id": "20",
    "fullName": "VAIBHAV ARORA",
    "nickname": "VICKY",
    "batch": "1994",
    "designation": "Group SVP",
    "organization": "Motilal Oswal",
    "profession": "Investment Banking",
    "qualification": "MBA",
    "city": "Noida",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "https://www.linkedin.com/in/vaibhav-arora-b28489163?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
    "facebookUrl": "",
    "registeredAt": "2026-03-27"
  },
  {
    "id": "21",
    "fullName": "Avijit Singh",
    "nickname": "Avijit",
    "batch": "1995",
    "designation": "",
    "organization": "",
    "profession": "Practicing as CA",
    "qualification": "Chartered accountant",
    "city": "New Delhi",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-03-27"
  },
  {
    "id": "22",
    "fullName": "Viren Jagdev",
    "nickname": "Viren",
    "batch": "1994",
    "designation": "",
    "organization": "",
    "profession": "Day trader US market",
    "qualification": "MBA",
    "city": "Dubai",
    "country": "United Arab Emirates",
    "photoUrl": "",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-03-27"
  },
  {
    "id": "23",
    "fullName": "Wing commander Ankur Singh",
    "nickname": "Chandel",
    "batch": "1998",
    "designation": "Senior Administrative Officer",
    "organization": "IAF",
    "profession": "Serving as an Officer in INDIAN AIR FORCE",
    "qualification": "BCA",
    "city": "Prayagraj",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-03-27"
  },
  {
    "id": "24",
    "fullName": "Amul Raj Singh",
    "nickname": "Mulli / Rikku",
    "batch": "1993",
    "designation": "Regional PF Commissioner-I",
    "organization": "EPFO",
    "profession": "Public Service",
    "qualification": "Post Graduation",
    "city": "New Delhi",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-03-27"
  },
  {
    "id": "25",
    "fullName": "Sumit Saini",
    "nickname": "Sumit",
    "batch": "1998",
    "designation": "CEO",
    "organization": "Shah Hospital",
    "profession": "Management Professional",
    "qualification": "MBA ELP",
    "city": "Gurugram",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-03-27"
  },
  {
    "id": "26",
    "fullName": "Shobhit Dhaka",
    "nickname": "Shobhit Dhaka",
    "batch": "1993",
    "designation": "",
    "organization": "TATA Communications Ltd",
    "profession": "",
    "qualification": "",
    "city": "Greater Noida",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-03-28"
  },
  {
    "id": "27",
    "fullName": "Parth sharma",
    "nickname": "Mogli",
    "batch": "2010",
    "designation": "CTO",
    "organization": "Kokumi tech",
    "profession": "Entrepreneur - scientist",
    "qualification": "MS",
    "city": "hannover",
    "country": "Germany",
    "photoUrl": "",
    "linkedinUrl": "https://www.linkedin.com/in/parthsharma16?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
    "facebookUrl": "",
    "registeredAt": "2026-03-28"
  },
  {
    "id": "28",
    "fullName": "Amit Gupta",
    "nickname": "Amit",
    "batch": "1994",
    "designation": "GM",
    "organization": "Shriram Finance Ltd.",
    "profession": "Finance",
    "qualification": "MBA Finance, Marketing and Banking",
    "city": "Noida",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-03-28"
  },
  {
    "id": "29",
    "fullName": "Prasoon Sheoran",
    "nickname": "Vicky",
    "batch": "1993",
    "designation": "Joint Director",
    "organization": "Health Department, Govt. Of Uttarakahnd",
    "profession": "Paediatrician and Public Health specialist",
    "qualification": "DNB",
    "city": "Faridabad",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-03-29"
  },
  {
    "id": "30",
    "fullName": "Gaurav Sankhyadhar",
    "nickname": "Golu",
    "batch": "94",
    "designation": "Promoter",
    "organization": "StepOne Spaces LLP",
    "profession": "Business",
    "qualification": "Graduate",
    "city": "Delhi",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-03-29"
  },
  {
    "id": "31",
    "fullName": "DR AMIT GAURAV",
    "nickname": "DRAG",
    "batch": "1994",
    "designation": "CONTROLLER OF EXAMINATIONS",
    "organization": "NOIDA INTERNATIONAL UNIVERSITY",
    "profession": "",
    "qualification": "PH.D.",
    "city": "Greater Noida",
    "country": "INDIA",
    "photoUrl": "",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-03-29"
  },
  {
    "id": "32",
    "fullName": "Anshu Rahal",
    "nickname": "Anshu",
    "batch": "1989",
    "designation": "Professor",
    "organization": "CvASc Gbpuat pantnagar",
    "profession": "Academician",
    "qualification": "Ph.D Animal Nutrition",
    "city": "Pantnagar",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-03-29"
  },
  {
    "id": "33",
    "fullName": "rajiv mishra",
    "nickname": "mishra",
    "batch": "1990",
    "designation": "owner",
    "organization": "universal energy solutions",
    "profession": "engineer",
    "qualification": "MBA",
    "city": "Delhi",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-03-29"
  },
  {
    "id": "34",
    "fullName": "Vinayak Pandey",
    "nickname": "Vinayak",
    "batch": "1992",
    "designation": "",
    "organization": "",
    "profession": "",
    "qualification": "",
    "city": "Phoenix",
    "country": "USA",
    "photoUrl": "",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-03-29"
  },
  {
    "id": "35",
    "fullName": "Amit Narang",
    "nickname": "Mintoo",
    "batch": "1992",
    "designation": "M D.",
    "organization": "Himalayan energy solutions",
    "profession": "Farmers/buisness",
    "qualification": "Post graduation/ LLB contd.",
    "city": "Rudrapur",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-03-29"
  },
  {
    "id": "36",
    "fullName": "Vikas Tewari",
    "nickname": "Vicky",
    "batch": "1997",
    "designation": "DGM Marketing",
    "organization": "Dhanuka Agritech",
    "profession": "SERVICE - AGRI",
    "qualification": "MBA",
    "city": "Gurugram",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "https://www.linkedin.com/in/vikas-t-a178611ba?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "facebookUrl": "",
    "registeredAt": "2026-03-29"
  },
  {
    "id": "37",
    "fullName": "Rahul Dube",
    "nickname": "Rahul",
    "batch": "1994",
    "designation": "",
    "organization": "TheKsquare group",
    "profession": "IT Director",
    "qualification": "Masters in IT",
    "city": "Hyderabad",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-03-29"
  },
  {
    "id": "38",
    "fullName": "Chetan Joshi",
    "nickname": "Daju",
    "batch": "1991",
    "designation": "Managing Director",
    "organization": "Bharatiya Beej Sahakari Samiti Ltd",
    "profession": "Service",
    "qualification": "Masters",
    "city": "New Delhi",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-03-29"
  },
  {
    "id": "39",
    "fullName": "Shalabh Varshney",
    "nickname": "SV",
    "batch": "1993",
    "designation": "CEO",
    "organization": "Balaji Hitech Pvt. Limited",
    "profession": "Service (Hybrid Mode)",
    "qualification": "MBA (Marketing & Finance)",
    "city": "Ghaziabad",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-03-29"
  },
  {
    "id": "40",
    "fullName": "Umesh Sisodia",
    "nickname": "Umesh",
    "batch": "1991",
    "designation": "Founder & CEO",
    "organization": "Circuitsutra Technologies Pvt Ltd",
    "profession": "Entrepreneur",
    "qualification": "B.Tech",
    "city": "Noida",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "https://www.linkedin.com/in/usisodia/",
    "facebookUrl": "https://www.facebook.com/umesh.sisodia/",
    "registeredAt": "2026-03-29"
  },
  {
    "id": "41",
    "fullName": "Tuhin Choudhary",
    "nickname": "Tuhin",
    "batch": "1995",
    "designation": "Colonel",
    "organization": "Indian Army",
    "profession": "Indian Army",
    "qualification": "Masters Double MA",
    "city": "Nagrota J and K",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-03-29"
  },
  {
    "id": "42",
    "fullName": "ViBHU DUTT",
    "nickname": "Rinku",
    "batch": "1994",
    "designation": "Manager Commercial",
    "organization": "Zee Media",
    "profession": "Commercial / Purchase",
    "qualification": "MBA",
    "city": "Dehradun",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-03-29"
  },
  {
    "id": "43",
    "fullName": "Kavinder Singh Rawat",
    "nickname": "Rikki",
    "batch": "1998",
    "designation": "Chief assistant",
    "organization": "State Education department Uttarakhand",
    "profession": "Education",
    "qualification": "M.A History",
    "city": "Haldwani",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-03-29"
  },
  {
    "id": "44",
    "fullName": "Abhishek singh",
    "nickname": "Bunny",
    "batch": "1994",
    "designation": "Executive architect",
    "organization": "IBM INDIA PVT LTD",
    "profession": "Executive architect",
    "qualification": "MBA",
    "city": "Greater Noida",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-03-30"
  },
  {
    "id": "45",
    "fullName": "Ronak Khurana",
    "nickname": "Ronak",
    "batch": "2007",
    "designation": "",
    "organization": "",
    "profession": "Intellectual Property Rights",
    "qualification": "",
    "city": "Noida",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-03-30"
  },
  {
    "id": "46",
    "fullName": "Nimish Airon",
    "nickname": "Nimish",
    "batch": "1989",
    "designation": "Executive Director",
    "organization": "3 Dimensional Insurance Brokers P Ltd",
    "profession": "Entrepreneur",
    "qualification": "MBA",
    "city": "Noida",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-03-30"
  },
  {
    "id": "47",
    "fullName": "ANUP ARORA",
    "nickname": "ANUP",
    "batch": "1990",
    "designation": "PRINCIPAL CONSULTANT",
    "organization": "SRI BALAJI ACTION MEDICAL INSTITUTE, PASCHIM VIHAR, NEW DELHI-110063",
    "profession": "DOCTOR",
    "qualification": "POST-GRADUATE (M.D. ANAESTHESIOLOGY)",
    "city": "Delhi",
    "country": "INDIA",
    "photoUrl": "",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-03-30"
  },
  {
    "id": "48",
    "fullName": "Ravi Gupta",
    "nickname": "Neeto",
    "batch": "1992",
    "designation": "MD",
    "organization": "M/s Om Prakash Ravi Prakash (Kichha),& RS Enterprises (Kichha)",
    "profession": "Buisness",
    "qualification": "Graduate (B.Sc.)",
    "city": "Kichha",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-04-02"
  },
  {
    "id": "49",
    "fullName": "Mohit Chadha",
    "nickname": "Mohit",
    "batch": "1998",
    "designation": "Partner",
    "organization": "Alaire Estate",
    "profession": "Luxury Real Estate in Gurgaon",
    "qualification": "Grad",
    "city": "Gurugram",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "https://www.linkedin.com/in/mohit-chadha/",
    "facebookUrl": "",
    "registeredAt": "2026-04-05"
  },
  {
    "id": "50",
    "fullName": "Abhiruchi Anand",
    "nickname": "Ruchi",
    "batch": "1989",
    "designation": "Doctor",
    "organization": "Own clinics",
    "profession": "Homeopathic Doctor",
    "qualification": "MS ( Psychotherapy & Counseling)",
    "city": "Delhi",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "https://www.linkedin.com/public-profile/settings/",
    "facebookUrl": "https://www.facebook.com/share/18d8neMqYf/",
    "registeredAt": "2026-04-05"
  },
  {
    "id": "51",
    "fullName": "Parvinder Singh",
    "nickname": "-",
    "batch": "1990",
    "designation": "",
    "organization": "Wipro Ltd",
    "profession": "IT Consulting",
    "qualification": "PGDBM",
    "city": "Faridabad",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-04-05"
  },
  {
    "id": "52",
    "fullName": "Meeta Maheshwari",
    "nickname": "Meeta",
    "batch": "1997",
    "designation": "Business Head",
    "organization": "J Rettenmaier & Sohne (JRS)",
    "profession": "Salaried",
    "qualification": "Ph.D.",
    "city": "Mumbai",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-04-06"
  },
  {
    "id": "53",
    "fullName": "Jitesh Pant",
    "nickname": "Jittu",
    "batch": "1994",
    "designation": "",
    "organization": "Entrepreneur",
    "profession": "Entrepreneur",
    "qualification": "MCA",
    "city": "Gurugram",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-04-06"
  },
  {
    "id": "54",
    "fullName": "Umesh Sisodia",
    "nickname": "Umesh",
    "batch": "1991",
    "designation": "Founder & CEO",
    "organization": "Circuitsutra Technologies Pvt Ltd",
    "profession": "Entrepreneur",
    "qualification": "B.Tech",
    "city": "Noida",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "https://www.linkedin.com/in/usisodia/",
    "facebookUrl": "https://www.facebook.com/umesh.sisodia",
    "registeredAt": "2026-04-13"
  },
  {
    "id": "55",
    "fullName": "Shipra Arora",
    "nickname": "Shipra",
    "batch": "2002",
    "designation": "Senior Dental surgeon",
    "organization": "Maulana Azad Institute of Dental sciences",
    "profession": "Doctor",
    "qualification": "Post graduate",
    "city": "New Delhi",
    "country": "India",
    "photoUrl": "",
    "linkedinUrl": "",
    "facebookUrl": "",
    "registeredAt": "2026-04-21"
  }
];
